version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/python:3.9
    environment: qgJsqEjzfSrlyZOLDyapdlYV7xcIrRq6C
      COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
    steps:
      - checkout

      - run:
          name: "Say hello"
          command: "echo Hello, World!"

      - run:
          name: "Install dependencies"
          command: PIPENV_SHELL=/bin/bash pipenv install --dev

      - run:
          name: "Run tests"
          command: pipenv run coverage run -m pytest 

      - run:
          name: "Generate Coverage report"
          command: pipenv run coverage report -m 

      - run:
          name: "Upload coverage"
          command: pipenv run coveralls

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
